### PR TITLE
migrate from tslint to eslint

### LINKED ISSUE #12: migration to eslint
saw that this new project had a `tsconfig.json` - since that's been deprecated for a while now and the recommended approach is to use eslint, were you looking for any help do a simple migration? i can make a pr

### PR DESCRIPTION
**Pull request by eankeen**
## Description
this migrates the linting config from tslint to eslint. a few changes were made to the source to comply with standard. closes #12

## Types of changes

- [ ] New framework or language
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the structure and style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] There is no duplicate pull request.
- [ ] My code passes all current tests, and passes new tests that I have written to test it if the current tests do not suffice.

### CODE REVIEW

**Comment by Cal-Hagner** [comment]
@eankeen Do you know what the issue is that's causing it to fail? Based on the error logs, it seems to be that your package.json is out of sync with your package-lock.json. Everything looks good except for the failing CI!

**Comment by eankeen** [comment]
yes i've been meaning to ask - are we using yarn or npm? i defaulted to yarn since i saw its lockfile but for some reason we have both - i can just remove the one we aren't using in this pr

**Comment by eankeen** [comment]
@Cal-Hagner checks now pass :)

**Comment by eankeen** [comment]
alright, good to go

**Comment by cjdenio** [comment]
We're getting more merge conflicts because we switched to Yarn :stuck_out_tongue_winking_eye: 
Fix those, and we should be good to go!

**Comment by eankeen** [comment]
@cjdenio you got it ;)

**Pull request merged**
