### PR TITLE
Yarn upgrade

### PR DESCRIPTION
**Pull request by cjdenio**
## Description

Upgraded to Yarn 2
## Related Issue

No linked issue. Sue me.
## Motivation and Context

YARN 2 FOREVER!!!
## Types of changes

- [ ] New framework or language
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the structure and style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] There is no duplicate pull request.
- [x] My code passes all current tests, and passes new tests that I have written to test it if the current tests do not suffice.

### CODE REVIEW

**Comment by Cal-Hagner** [comment]
Should we add `yarn.lock` to the .gitignore?

**Comment by cjdenio** [comment]
No, it's supposed to be committed.

**Comment by cjdenio** [comment]
It seems like it's a problem with ESLint. :confused:

**Comment by Cal-Hagner** [comment]
If anyone would like to make an infrastructure shift, we will be using Yarn 2 from now on because we want to and that's what is currently working. Please open a separate issue and open a PR for any changes you make.

**Pull request merged**
