### PR TITLE
Add Features

### PR DESCRIPTION
**Pull request by cjdenio**
## Description
This PR makes the CLI work, because it didn't before. It's far from done, but it's functional.

## Related Issue
Doesn't completely fix any issue

## Motivation and Context

*\*yawn\**

## Screenshots (if applicable):
[asciicast](https://asciinema.org/a/334410)

image

## Types of changes

- [ ] New framework or language
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the structure and style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. **(we don't have one?)**
- [x] There is no duplicate pull request.
- [x] My code passes all current tests, and passes new tests that I have written to test it if the current tests do not suffice.

### CODE REVIEW

**Comment by Cal-Hagner** [comment]
@cjdenio Wait! Please don't merge, I have changes I'm working on locally on `cjdeniotestbranch` that will be pushed later today.

**Comment by cjdenio** [comment]
No worries, just let me know (or merge) once you're done!

I find it funny that we're actually doing development on a branch named after me :joy:

**Comment by Cal-Hagner** [comment]
@cjdenio This code is dirty, but it's functional. Once it's merged, we can clean it up and add the commit caching so that we stay in line with structures up top. Right now, this has basic (non-tracking) caches that can be reused.

**Comment by cjdenio** [comment]
Awesome! One little thing: it would be great if you ran `npm run format` _before_ pushing, just to keep the diffs normal-looking. Thanks!

**Comment by Matt-Gleich** [comment]
It might make sense to make it a git hook

**Comment by Cal-Hagner** [comment]
I know, I'm working on it. This is new territory for me.

**Comment by Matt-Gleich** [comment]
No worries, keep in mind you can also amend commits. I do it all the time when I forget to format code or something like that. It also counts as a push so it will re-trigger the CI.
https://support.gitkraken.com/working-with-commits/commits/

**Pull request merged**
