### PR TITLE
ensure `package.json` scripts are more cross-platform

### LINKED ISSUE #17: ensure `package.json` scripts are more cross platform
right now the `scripts` entries in the `package.json` are not cross platform (won't work on windows). (ex. shell-dependent glob behavior, bash / shell logical evaluation operators, use of shell / bash builtins etc.)., if needed i can clean this up an ensure a more consistent cross platform experience - can make a pr for this

### PR DESCRIPTION
**Pull request by eankeen**
## Description
this pr closes #17 by replacing non cross-platform scripts with portable ones, primarily the packages `npm-run-all` and `rimraf`. see the commit messages for details

i also snuck in a renaming of `bin/cli` to `bin/cli.js`, since previously the file would be skipped by the linters

## Types of changes

- [ ] New framework or language
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the structure and style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] There is no duplicate pull request.
- [x] My code passes all current tests, and passes new tests that I have written to test it if the current tests do not suffice.

### CODE REVIEW

**Comment by Cal-Hagner** [comment]
@eankeen I'll resolve these conflicts and merge this PR. Thank you again!

**Comment by cjdenio** [comment]
Yarn 2 actually runs scripts in its own shell, so this might not have been necessary. Thanks, though!

**Comment by eankeen** [comment]
@cjdenio you're using yarn, not yarn 2

glad i could help :)

**Comment by Cal-Hagner** [comment]
@eankeen We're actually trying to shift to using Yarn 2. If you have any experience, we would gladly welcome it... we've been having some issues migrating.

**Comment by eankeen** [comment]
oh neat, i didn't see that pr. i'll take a look at it

**Comment by Cal-Hagner** [comment]
It's #27.

**Comment by Cal-Hagner** [comment]
I will also add you to the Slack channel for this project so you can see our discussions.

**Pull request merged**
